### ISSUE TITLE
AttributeError: 'GCNConfig' object has no attribute 'em_info'

### ISSUE THREAD

**Issue by Ldtenacity** [AndyJZhao/GLEM#10]
When execute python GLEM/src/models/GNNs/trainGNN.py

The following error happens

Traceback (most recent call last):
  File "GLEM/src/models/GNNs/trainGNN.py", line 12, in <module>
    cf = Config(args).init()
  File "/afs/crc.nd.edu/user/d/dliu9/GLEM/src/utils/modules/conf_utils.py", line 61, in init
    self._exp_init()
  File "/afs/crc.nd.edu/user/d/dliu9/GLEM/src/models/GNNs/gnn_utils.py", line 63, in _exp_init
    super()._exp_init()
  File "/afs/crc.nd.edu/user/d/dliu9/GLEM/src/utils/modules/conf_utils.py", line 45, in _exp_init
    self._data_args_init()
  File "/afs/crc.nd.edu/user/d/dliu9/GLEM/src/models/GNNs/gnn_utils.py", line 86, in _data_args_init
    self.lm_md = self.em_info.lm_md
AttributeError: 'GCNConfig' object has no attribute 'em_info'

**Comment by hanghangqiu** [comment]
请问找到解决方法了吗
