### ISSUE TITLE
sh: 1: /home/gyn/miniconda/envs/ct/bin/torchrun: not found

### ISSUE THREAD

**Issue by yanniangu** [AndyJZhao/GLEM#11]
when running `python src/models/GLEM/trainGLEM.py --dataset=arxiv_TA --em_order=LM-first --gnn_ckpt=RevGAT --gnn_early_stop=300 --gnn_epochs=2000 --gnn_input_norm=T --gnn_label_input=F --gnn_model=RevGAT --gnn_pl_ratio=1 --gnn_pl_weight=0.05 --inf_n_epochs=2 --inf_tr_n_nodes=100000 --lm_ce_reduction=mean --lm_cla_dropout=0.4 --lm_epochs=3 --lm_eq_batch_size=30 --lm_eval_patience=30460 --lm_init_ckpt=None --lm_label_smoothing_factor=0 --lm_load_best_model_at_end=T --lm_lr=2e-05 --lm_model=Deberta --lm_pl_ratio=1 --lm_pl_weight=0.8 --pseudo_temp=0.2  --gpus=0`, there is an error:

```
 <<<<<<<<<< LM-Pretraining >>>>>>>>>>
Running command:
CUDA_VISIBLE_DEVICES=0 /home/gyn/miniconda/envs/ct/bin/torchrun --master_port=44135 --nproc_per_node=1 src/models/LMs/trainLM.py -mDeberta --att_dropout=0.1 --cla_dropout=0.4 --dropout=0.3 --epochs=4 --eq_batch_size=36 --eval_patience=50000 --label_smoothing_factor=0.3 --load_best_model_at_end=T --lr=2e-05 --warmup_epochs=0.6 --save_folder=/data/gyn/GLEM/temp/prt_lm/arxiv_TA/Deberta/FtV1/ -darxiv_TA -g0  --em_iter=-1
sh: 1: /home/gyn/miniconda/envs/ct/bin/torchrun: not found
Traceback (most recent call last):
  File "src/models/GLEM/trainGLEM.py", line 22, in <module>
    train_glem(args)
  File "/data/gyn/GLEM/src/utils/function/os_utils.py", line 283, in wrapper
    ret = func(*args, **kw)
  File "src/models/GLEM/trainGLEM.py", line 16, in train_glem
    GLEMTrainer(cf).glem_train()
  File "/data/gyn/GLEM/src/models/GLEM/GLEM_trainer.py", line 136, in glem_train
    self._pre_train_lm()  # Get LM emb + pred
  File "/data/gyn/GLEM/src/models/GLEM/GLEM_trainer.py", line 56, in _pre_train_lm
    uf.run_command_parallel(cmd, gpus, self.log)
  File "/data/gyn/GLEM/src/utils/function/os_utils.py", line 10, in run_command_parallel
    run_command(cmd, log_func)
  File "/data/gyn/GLEM/src/utils/function/os_utils.py", line 17, in run_command
    raise ValueError(f'Failed to operate {cmd}')
ValueError: Failed to operate CUDA_VISIBLE_DEVICES=0 /home/gyn/miniconda/envs/ct/bin/torchrun --master_port=44135 --nproc_per_node=1 src/models/LMs/trainLM.py -mDeberta --att_dropout=0.1 --cla_dropout=0.4 --dropout=0.3 --epochs=4 --eq_batch_size=36 --eval_patience=50000 --label_smoothing_factor=0.3 --load_best_model_at_end=T --lr=2e-05 --warmup_epochs=0.6 --save_folder=/data/gyn/GLEM/temp/prt_lm/arxiv_TA/Deberta/FtV1/ -darxiv_TA -g0  --em_iter=-1
```

**Comment by AndyJZhao** [comment]
You need to replace '/home/gyn/miniconda/envs/ct/bin/torchrun' to your own environment.

**Comment by ZhuWenxuan123code** [comment]
do you solve the question？my path is right，but still report this error
