### ISSUE TITLE
sh: 1: /home/public207/miniconda/envs/ct/bin/torchrun: not found

### ISSUE THREAD

**Issue by czjdsg** [AndyJZhao/GLEM#7]
When running ```python src/models/GLEM/trainGLEM.py```, there is an error.

```
Running command:
CUDA_VISIBLE_DEVICES=0 /home/public207/miniconda/envs/ct/bin/torchrun --master_port=52105 --nproc_per_node=1 src/models/LMs/trainLM.py -mTinyBert --att_dropout=0.1 --cla_dropout=0.4 --dropout=0.3 --epochs=4 --eq_batch_size=36 --eval_patience=50000 --label_smoothing_factor=0.3 --load_best_model_at_end=T --lr=2e-05 --warmup_epochs=0.6 --save_folder=/data1/czj/GLEM-main/temp/prt_lm/arxiv_TA_0.002/TinyBert/FtV1/ -darxiv_TA_0.002 -g0  --em_iter=-1
sh: 1: /home/public207/miniconda/envs/ct/bin/torchrun: not found
Traceback (most recent call last):
  File "src/models/GLEM/trainGLEM.py", line 22, in <module>
    train_glem(args)
  File "/data1/czj/GLEM-main/src/utils/function/os_utils.py", line 283, in wrapper
    ret = func(*args, **kw)
  File "src/models/GLEM/trainGLEM.py", line 16, in train_glem
    GLEMTrainer(cf).glem_train()
  File "/data1/czj/GLEM-main/src/models/GLEM/GLEM_trainer.py", line 136, in glem_train
    self._pre_train_lm()  # Get LM emb + pred
  File "/data1/czj/GLEM-main/src/models/GLEM/GLEM_trainer.py", line 56, in _pre_train_lm
    uf.run_command_parallel(cmd, gpus, self.log)
  File "/data1/czj/GLEM-main/src/utils/function/os_utils.py", line 10, in run_command_parallel
    run_command(cmd, log_func)
  File "/data1/czj/GLEM-main/src/utils/function/os_utils.py", line 17, in run_command
    raise ValueError(f'Failed to operate {cmd}')
```

**Comment by ShichangZh** [comment]
May I ask how you fixed the issue? I am encountering the same issue. Thanks.
